### ISSUE TITLE
the image sources path problem about spm build css ?

### ISSUE THREAD

**Issue by jpuncle** [spmjs/spm#1090]
I have a module,

```
package.json
index.css
src/
    help.css
    logo.png
```

index.css
```css
@import "./src/help.css"
```

src/help.css
```css
.btn .btn-red {
    color: #f00;
    background: url(./logo.png);
}
```

package.json
```
"main": "index.js",
"output": ["index.css", "src/logo.png"]
```

the spm build result,
index.css
```css
.btn .btn-red{color:red;background:url(./logo.png)}
```

the image path in the index.css is wrong, **should normalize the path**.
