### ISSUE TITLE
spm search 时，无效信息太多

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#481]
希望精简一下。

```
➜  tip git:(master) spm search arale.tip
query: $..[?(@.name=="tip"&&@.root=="arale")]
Downloading: http://modules.alipay.im:7000/arale/config.json
Downloading: http://modules.alipay.im:7000/config.json
Downloaded: http://modules.alipay.im:7000/config.json
Downloaded: http://modules.alipay.im:7000/arale/config.json
find requestUrl---> /Users/afc163/.spm/sources/spm/online-status/1.0.0/check.js
HTTP HEAD 200 http://modules.alipay.im:7000
HTTP HEAD 200 http://modules.spmjs.org
Downloading: http://modules.alipay.im:7000/info.json
Downloaded: http://modules.alipay.im:7000/info.json
Downloading: http://modules.alipay.im:7000/psbp/info.json
Downloading: http://modules.alipay.im:7000/alipay/info.json
Downloading: http://modules.alipay.im:7000/consumeprod/info.json
Downloading: http://modules.alipay.im:7000/handy/info.json
Downloading: http://modules.alipay.im:7000/template/info.json
Downloading: http://modules.alipay.im:7000/wapcashier/info.json
Downloading: http://modules.alipay.im:7000/clive/info.json
Downloading: http://modules.alipay.im:7000/spm/info.json
Downloaded: http://modules.alipay.im:7000/handy/info.json
Downloaded: http://modules.alipay.im:7000/template/info.json
Downloaded: http://modules.alipay.im:7000/psbp/info.json
Downloaded: http://modules.alipay.im:7000/alipay/info.json
Downloaded: http://modules.alipay.im:7000/consumeprod/info.json
Downloaded: http://modules.alipay.im:7000/wapcashier/info.json
Downloaded: http://modules.alipay.im:7000/clive/info.json
Downloaded: http://modules.alipay.im:7000/spm/info.json
Downloading: http://modules.spmjs.org/info.json
Downloaded: http://modules.spmjs.org/info.json
Downloading: http://modules.spmjs.org/arale/info.json
Downloading: http://modules.spmjs.org/gallery/info.json
Downloading: http://modules.spmjs.org/template/info.json
Downloaded: http://modules.spmjs.org/template/info.json
Downloaded: http://modules.spmjs.org/arale/info.json
Downloaded: http://modules.spmjs.org/gallery/info.json
- 
  0.9.2: 
    - atip.js
    - tip.js
  root:        arale
  name:        tip
  tag:         widget
  type:        
  description: 基础提示框组件，用于带箭头的 hover 提示框显示和隐藏。
  versions: 
    0.9.2: 
      - tip.js
      - atip.js
Total time: 5.799s
Finished at: Wed Dec 05 2012 14:13:44 GMT+0800 (CST)
Final Memory: 31M/60M
```
